### ISSUE TITLE
Attribute feature_importances_

### ISSUE THREAD

**Issue by rrealrangel** [saattrupdan/doubt#32]
Hi. First of all, I hope this is the correct way to point this out. As a user, I am not familiar with developer protocols. I am using the **QuantileRegressionForest** class and have noticed that the **'feature_importances_'** attribute is not available for my trained model. Is there any way to access this attribute? Do you plan to incorporate it in a future version? Thanks in advance. (By the way, thanks for sharing the module).

**Comment by saattrupdan** [comment]
Hi, and thanks for your interest in `doubt`!

I agree that this would be a good feature to have. The individual trees should support this already, but the forests do not. We could use [the original sklearn implementation](https://github.com/scikit-learn/scikit-learn/blob/8b6b519caf3b3b9602958a859b4d3a7eb1d9eadd/sklearn/ensemble/_forest.py#L605-L640) here. I'll implement it as soon as I got the time 🙂

**Comment by saattrupdan** [comment]
@rrealrangel  Implemented, after quite a long delay, in [v4.3.0](https://github.com/saattrupdan/doubt/releases/tag/v4.3.0) 🎉
