### ISSUE TITLE
Tree estimates in quantile regression forest

### ISSUE THREAD

**Issue by gugerlir** [saattrupdan/doubt#52]
Dear Dan Saattrup Nielsen, 

First of all, thank you very much for your python package with the quantile regression forests (QRF)! We are very interested in using this package. 

While running the QRF, however, I tried to extract the estimates of each tree. But, the estimate was exactly the same for all trees. Hence, I was wondering whether this is done on purpose and/or a result of the design of your QRF? Is it linked to the lines 137:148 in doubt.models.tree.forest.py, which appear to be different in the skgarden package?

Thank you very much!
gugerlir

**Comment by saattrupdan** [comment]
Hi @gugerlir

Thanks for your feedback. It does indeed seem like I'm just copying the same tree rather than initialising new ones - nice catch!

I'll update it in a patch update later today or tomorrow 😊

**Comment by saattrupdan** [comment]
This should be fixed in the newest patch release (v4.3.1), and closing now. Feel free to re-open if it didn't fix the issue 🙂

**Comment by gugerlir** [comment]
Awesome! Thank you so much for taking care of the bug so fast! It works perfectly now!! :)
